# Generated by Django 5.2.8 on 2025-11-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='known_for',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='nationality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='notable_work',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
